Updated workflow to release floating tags

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,4 +1,4 @@
-name: Publish Docker Image to GHCR
+name: Release new version
 
 on:
   release:
@@ -37,3 +37,26 @@ jobs:
         push: true
         tags: ${{ steps.meta.outputs.tags }}
         labels: ${{ steps.meta.outputs.labels }}
+
+  create-floating-tag:
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v3
+
+    - name: Set major version
+      run: |
+        git config --local user.email "actions@github.com"
+        git config --local user.name "GitHub Actions"
+
+        current_version=${{github.event.release.tag_name}}
+        if [[ ! "$current_version" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+          echo "Error: current_version does not follow semantic versioning (vX.Y.Z)."
+          exit 1
+        fi
+
+        major_version="${version%%.*}"
+        git tag -d "$major_version" 2>/dev/null || echo "Tag $major_version not found."
+        git tag $major_version $current_version
+        git push origin $major_version --force
